name: tour_around
description: Find touristic landmarks around you, easily.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  date_field: ^3.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  flutter_google_places: ^0.3.0
  flutter_polyline_points: ^1.0.0
  flutter_stripe: ^9.0.0+1
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.0.9
  geolocator: ^9.0.1
  get: ^4.6.5
  google_api_headers: ^1.3.0
  google_maps_flutter: ^2.1.12
  google_maps_webservice: ^0.0.19
  google_sign_in: ^5.4.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  location: ^4.4.0
  objectbox: ^1.7.2
  objectbox_generator: ^1.7.2
  objectbox_sync_flutter_libs: any
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  settings_ui: ^2.0.2
  sqflite: ^2.0.3+1
  twitter_login: ^4.2.3
  uuid: ^3.0.6
  weather: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita_Regular.otf
        - asset: assets/fonts/Gordita_Medium.otf
          weight: 500
        - asset: assets/fonts/Gordita_Bold.otf
          weight: 700
        - asset: assets/fonts/Gordita_Light.otf
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
